# Generated by Django 6.0.1 on 2026-02-11 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=datetime.datetime(2026, 2, 11, 4, 34, 26, 70319, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
