# Generated by Django 6.0.1 on 2026-02-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_blogcategory_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
