# Generated by Django 6.0.1 on 2026-01-28 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pancard',
            field=models.FileField(default=datetime.datetime(2026, 1, 28, 8, 6, 39, 835321, tzinfo=datetime.timezone.utc), upload_to='users_pancards/'),
            preserve_default=False,
        ),
    ]
