# Generated by Django 6.0.1 on 2026-01-28 08:12

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pancard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pancard',
            field=models.FileField(upload_to=apps.users.models.pancard_upload_path),
        ),
    ]
