# Generated by Django 6.0.1 on 2026-02-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
