# Generated by Django 6.0.1 on 2026-02-04 04:20

import apps.users.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='companyProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(default='default/company.png', upload_to=apps.users.models.company_logo_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='socialLinks',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
