# Generated by Django 6.0.1 on 2026-02-05 04:35

import apps.users.models
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_services_companyprofile_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='services',
        ),
        migrations.RemoveField(
            model_name='sociallinks',
            name='company',
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2026, 2, 5, 4, 35, 45, 197644, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default/company.png', upload_to=apps.users.models.company_logo_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_by_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to='users.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='companies', to='users.service'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='companyProfile',
        ),
    ]
