# Generated by Django 6.0.1 on 2026-02-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_companyprofile_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
